services:
  vector:
    image: timberio/vector:latest-alpine
    volumes:
      - ./vector:/etc/vector
    command: ["-c", "/etc/vector/vector.yaml"]
    ports:
      - '514:514/udp'
    container_name: vector
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    container_name: loki
